
export const teacher_names = [
        "Abhaya Kumar Sahoo",
        "Abhishek Raj",
        "Abhishek Ray",
        "Abinas Panda",
        "Adyasha Dash",
        "Ajay Anand",
        "Ajay Kumar Jena",
        "Ajaya Kumar Parida",
        "Ajit Kumar Pasayat",
        "Aleena Swetapadma",
        "Alok Kumar Jagadev",
        "Ambika Prasad Mishra",
        "Amiya Kumar Dash",
        "Amiya Ranjan Panda",
        "Amulya Ratna Swain",
        "Anil Kumar Swain",
        "Anirban Bhattacharjee",
        "Anjan Bandyopadhyay",
        "Anuja Kumar Acharya",
        "Aradhana Behura",
        "Arup Abhinna Acharya",
        "Arup Sarkar",
        "Ashish Singh",
        "Asif Uddin Khan",
        "Banchhanidhi Dash",
        "Benazir Neha",
        "Bhabani Shankar Prasad Mishra",
        "Bhaswati Sahoo",
        "Bindu Agarwalla",
        "Chandani Kumari",
        "Chandra Shekhar",
        "Chittaranjan Pradhan",
        "Dayal Kumar Behera",
        "Debanjan Pathak",
        "Debashis Hati",
        "Deependra Singh",
        "Dipti Dash",
        "G B Mund",
        "Gananath Bhuyan",
        "Harish Kumar Patnaik",
        "Himansu Das",
        "Hitesh Mohapatra",
        "Hrudaya Kumar Tripathy",
        "Ipsita Paul",
        "Jagannath Singh",
        "Jasaswi Prasad Mohanty",
        "Jay Sarraf",
        "Jayanta Mondal",
        "Jayanti Dansana",
        "Jayeeta Chakraborty",
        "Jhalak Hota",
        "Joy Dutta",
        "Junali Jasmine Jena",
        "Jyotiprakash Mishra",
        "Krishna Chakravarty",
        "Krishnandu Hazra",
        "Krutika Verma",
        "Kumar Devadutta",
        "Kunal Anand",
        "Lalit Kumar Vashishtha",
        "Leena Das",
        "Lipika Dewangan",
        "Lipika Mohanty",
        "M Nazma BJ Naskar",
        "Madhabananda Das",
        "Mahendra Kumar Gourisaria",
        "Mainak Bandyopadhyay",
        "Mainak Biswas",
        "Mainak Chakraborty",
        "Manas Ranjan Biswal",
        "Manas Ranjan Lenka",
        "Manas Ranjan Nayak",
        "Mandakini Priyadarshani Behera",
        "Manjusha Pandey",
        "Manoj Kumar Mishra",
        "Meghana G Raj",
        "Minakhi Rout",
        "Mohit Ranjan Panda",
        "Monideepa Roy",
        "Mukesh Kumar",
        "Murari Mandal",
        "N Biraja Isac",
        "Nachiketa Tarasia",
        "Naliniprava Behera",
        "Namita Panda",
        "Nibedan Panda",
        "Niranjan Kumar Ray",
        "Partha Pratim Sarangi",
        "Partha Sarathi Paul",
        "Pinaki Sankar Chatterjee",
        "Prabhu Prasad Dev",
        "Prachet Bhuyan",
        "Pradeep Kandula",
        "Pradeep Kumar Mallick",
        "Prasant Kumar Pattnaik",
        "Prasenjit Maiti",
        "Pratyusa Mukherjee",
        "Priyanka Roy",
        "Rabi Shaw",
        "Raghunath Dey",
        "Rajat Kumar Behera",
        "Rajdeep Chatterjee",
        "Ramakant Parida",
        "Ramesh Kumar Thakur",
        "Rina Kumari",
        "Rinku Datta Rakshit",
        "Ronali Padhy",
        "Roshni Pradhan",
        "Saikat Chakraborty",
        "Samaresh Mishra",
        "Sampriti Soor",
        "Sankalp Nayak",
        "Santos Kumar Baliarsingh",
        "Santosh Kumar Pani",
        "Santosh Kumar Swain",
        "Santwana Sagnika",
        "Sarita Mishra",
        "Sarita Tripathy",
        "Satarupa Mohanty",
        "Satyananda Champati Rai",
        "Saurabh Bilgaiyan",
        "Saurabh Jha",
        "Shaswati Patra",
        "Shilpa Das",
        "Siddharth Swarup Rautaray",
        "Soumya Ranjan Mishra",
        "Soumya Ranjan Nayak",
        "Sourajit Behera",
        "Sourav Kumar Giri",
        "Sovan Kumar Sahoo",
        "Subhadip Pramanik",
        "Subhashree Darshana",
        "Subhasis Dash",
        "Suchismita Das",
        "Suchismita Rout",
        "Sujata Swain",
        "Sujoy Datta",
        "Suneeta Mohanty",
        "Suresh Chandra Satapathy",
        "Sushruta Mishra",
        "Susmita Das",
        "Swagatika Sahoo",
        "Tanik Saikh",
        "Tanmaya Swain",
        "Tanmoy Maitra",
        "Vijay Kumar Meena",
        "Vikas Hassija"
    ]
    
    
// const TeacherNamesSelect = () => {
//     return (
//     <div>
//         <label htmlFor="teacherSelect">Select a Teacher:</label>
//         <select id="teacherSelect">
//         {teacher_names.map((name, index) => (
//             <option key={index} value={name}>
//             {name}
//             </option>
//         ))}
//         </select>
//     </div>
//     );
// };


// export default TeacherNamesSelect;